apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: newnew-gitops
  description: This is GitOps manifest for newnew   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: newnew
    janus-idp.io/tekton: newnew 
    backstage.io/kubernetes-id: newnew 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:newnew
