apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: newnew
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: newnew 
  name: newnew
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: newnew 
